### ISSUE TITLE
Travis CI fails to download covr

### ISSUE THREAD

**Issue by phillc73** [jimhester/covr#149]
Not sure if this is the right place to leave this report, but nonetheless, I'll start here. It might be a devtools issue for @hadley

My Travis CI build for the R package [backblazer](https://github.com/phillc73/backblazer) is failing with the following:

`
Installing R packages from GitHub: jimhester/covr
0.60s$ Rscript -e 'devtools::install_github(c("jimhester/covr"), build_vignettes = FALSE)'
Downloading GitHub repo jimhester/covr@master
from URL https://api.github.com/repos/jimhester/covr/zipball/master
Error in download(dest, src, auth) : Forbidden (HTTP 403).
Calls: <Anonymous> ... remote_download.github_remote -> download -> <Anonymous>
Execution halted
The command "Rscript -e 'devtools::install_github(c("jimhester/covr"), build_vignettes = FALSE)'" failed and exited with 1 during .
Your build has been stopped.
`

My .travis.yml file contains the following:

```yml
language: R
cache: packages

warnings_are_errors: true

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
```

[Failed Travis CI build details](https://travis-ci.org/phillc73/backblazer/builds/109714487)

I have recently made some pacakge updates, but the Travis CI error doesn't seem to be related to them.
