### ISSUE TITLE
No connection between travis CI and coveralls?

### ISSUE THREAD

**Issue by cdeterman** [jimhester/covr#83]
I have been trying to use coveralls for my R package but I cannot seem to get the information connected on my coveralls account.  I am using Travis CI and my package is building successfully [see here](https://travis-ci.org/cdeterman/OmicsMarkeR/builds/60589558).

But my coveralls repo shows nothing, not even my master branch which you can see [here](https://coveralls.io/r/cdeterman/OmicsMarkeR).

Have I missed something simple here?

Here is my .travis.yml file as well

```
language: r
bioc_required: true
r_packages: XML

sudo: required

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_bioc BiocStyle
  - ./travis-tool.sh install_bioc_deps
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh github_package jimhester/covr

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
```
